server:
  port: 8081

spring:
  application:
    name: EmployeeDashBoard
    
  cloud:
    config:
      uri: http://localhost:8888
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka
  
 

  
#  instance:
#    prefer-ip-address: true