server:
  port: 8080
  address: localhost

spring:
  application:
    name: EmployeeSearchService
  cloud:
    config:
      uri: http://localhost:8888

  
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  server:
    servlet:
      context-path: /actuator
      
        
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:9091/eureka/


  instance:
    statusPageUrlPath: ${management.server.servlet.context-path}/info
    healthCheckUrlPath: ${management.server.servlet.context-path}/health
